# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291d2667fb3c7c7ae0c5ca9da6358e3c2994c3d7c8a517fe3d41765060aa339f9c1fd6c4cab817b1dbbf2d669e8446df0f7586f0f42857f7039dae4726c2723a

test:
  secret_key_base: 2f771a124d8453b496b3b80ce862dd7ce98cc4ba92adac347a32fb79d78236ee347704d7d767b38f51bc1c2d3766b6c3b4e6b0861c94ccb6cebf68f1030ea3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
